<?php
$auto_reviews_ship = array(
    array("name" => "Damiano H.", "text" => "Non ho dovuto aspettare molto, consegna gestita in modo professionale."),
    array("name" => "Vincenzo M.", "text" => "La consegna è stata estremamente veloce e ho ricevuto tutte le informazioni via email e SMS. Mi è piaciuto particolarmente che il corriere abbia chiamato prima di arrivare. Mi sono sentito come se tutto fosse organizzato su misura per il cliente."),
    array("name" => "Stanislao P.", "text" => "Tutto arrivato in tempo, corriere molto gentile."),
    array("name" => "Nicola V.", "text" => "Imballaggio davvero di qualità, si vede l'impegno."),
    array("name" => "Matteo K.", "text" => "Il pacco è arrivato intatto e ottimamente imballato. Tutto era protetto in modo che non c'è possibilità che qualcosa si danneggi durante il trasporto. Grandi complimenti per la professionalità."),
    array("name" => "Marco C.", "text" => "Servizio di consegna senza errori."),
    array("name" => "Leone T.", "text" => "Il corriere è stato cortese e gentile, e la consegna puntuale al minuto. Il pacco era ordinatamente riposto e senza alcun danno. Sono molto soddisfatto."),
    array("name" => "Zarko T.", "text" => "Consegna molto veloce e ottima coordinazione."),
    array("name" => "Branimir S.", "text" => "Servizio di alto livello, tutto chiaro."),
    array("name" => "Cristiano O.", "text" => "L'imballaggio era molto ordinato e sicuro. Non c'erano danni e la consegna è arrivata nel termine concordato. Da parte mia solo complimenti."),
    array("name" => "Sandro J.", "text" => "Imballato ordinatamente e consegnato in sicurezza."),
    array("name" => "Tommaso R.", "text" => "Pacco arrivato prima del previsto."),
    array("name" => "Ivan B.", "text" => "Tutto arrivato prima di quanto mi aspettassi."),
    array("name" => "Domenico C.", "text" => "La consegna è stata puntuale e veloce."),
    array("name" => "Sandro U.", "text" => "La consegna è stata veloce e l'imballaggio molto ordinato. L'assistenza era disponibile anche fuori orario di lavoro. Consiglio a chiunque voglia un acquisto senza preoccupazioni."),
    array("name" => "Mirko C.", "text" => "Confezione ordinata e di qualità."),
    array("name" => "Željko R.", "text" => "L'assistenza clienti ha risposto rapidamente alla mia domanda sui tempi di consegna. Il pacco è arrivato anche prima di quanto indicato sul sito. Consigliato al cento per cento."),
    array("name" => "Sandro L.", "text" => "Procedura di ritiro molto semplice."),
    array("name" => "Tommaso P.", "text" => "Consegna veloce e ritiro semplice."),
    array("name" => "Dario S.", "text" => "Servizio molto buono."),
    array("name" => "Siniša H.", "text" => "Dal momento dell'ordine alla consegna tutto è andato liscio. Ho sempre avuto visibilità sullo stato della spedizione e questo mi ha dato fiducia. Servizio di alta qualità."),
    array("name" => "Pietro V.", "text" => "La consegna è stata veloce."),
    array("name" => "Filippo P.", "text" => "Il pacco è arrivato in 2 giorni, cosa che mi ha molto sorpreso. L'imballaggio era di qualità e ordinato, proprio come deve essere. Sicuramente ordinerò di nuovo."),
    array("name" => "Antonio F.", "text" => "Tutto è andato liscio."),
    array("name" => "Mario D.", "text" => "Pacco arrivato prima del termine previsto."),
    array("name" => "Nicola J.", "text" => "Pacco arrivato intatto."),
    array("name" => "Biagio I.", "text" => "Ordinare è stato semplice e la consegna ancora più semplice. Tutte le informazioni di tracciamento erano chiare e aggiornate. Servizio top."),
    array("name" => "Ivan K.", "text" => "Nessuna lamentela."),
    array("name" => "Dino A.", "text" => "Ho seguito la consegna online e tutto ha funzionato perfettamente. Il pacco è arrivato in anticipo e ben imballato. Tutti i dettagli erano disponibili in tempo."),
    array("name" => "Hrvoje M.", "text" => "Ho ricevuto subito tutte le informazioni di tracciamento."),
    array("name" => "Bojan R.", "text" => "Imballaggio ordinato, arrivato sicuro e intatto."),
    array("name" => "Andrea Z.", "text" => "La consegna è stata più veloce di quanto scritto."),
    array("name" => "Darko G.", "text" => "Assistenza sempre disponibile."),
    array("name" => "Vlado F.", "text" => "Non ho avuto nessun problema, tutto liscio."),
    array("name" => "Ivan Z.", "text" => "L'assistenza clienti è stata molto disponibile e mi ha risposto rapidamente. La consegna è arrivata prima di quanto indicato nella notifica. Consiglio a tutti."),
    array("name" => "Alessandro V.", "text" => "Molto soddisfatto."),
    array("name" => "Mirko B.", "text" => "Consegna molto veloce."),
    array("name" => "Giuseppe G.", "text" => "Imballato ordinatamente e consegnato velocemente."),
    array("name" => "Hrvoje D.", "text" => "Dopo l'ordine tutto è andato molto velocemente. Il pacco era pronto e spedito lo stesso giorno, ed è arrivato già il giorno dopo. Ottima esperienza."),
    array("name" => "Nino T.", "text" => "Elaborazione rapida dell'ordine, eccellente."),
    array("name" => "Antonio H.", "text" => "Raramente si vede un servizio così professionale."),
    array("name" => "Giorgio J.", "text" => "Ho ordinato lunedì e il pacco è arrivato già mercoledì. L'intero processo è stato semplice e trasparente. Sono molto soddisfatto."),
    array("name" => "Nicola T.", "text" => "La consegna è stata più veloce di quanto mi aspettassi. Ho ricevuto una notifica in ogni fase, il che mi ha dato fiducia. Servizio molto professionale."),
    array("name" => "Alessandro F.", "text" => "Pacco arrivato in anticipo."),
    array("name" => "Marco Z.", "text" => "L'intero processo di consegna è stato semplice."),
    array("name" => "Ivan L.", "text" => "Subito dopo l'ordine ho ricevuto la conferma e il numero di tracciamento. Il pacco è arrivato intatto e in tempo. Il servizio merita un bel dieci."),
    array("name" => "Cristiano N.", "text" => "Pacco arrivato in condizioni perfette."),
    array("name" => "Mariano D.", "text" => "Ho solo parole di elogio – dall'ordine alla consegna tutto è stato gestito professionalmente. Il corriere mi ha chiamato prima della consegna e tutto è andato senza stress. Complimenti."),
    array("name" => "Damiano A.", "text" => "Molto soddisfatto del servizio."),
    array("name" => "Roberto S.", "text" => "Servizio clienti eccellente."),
    array("name" => "Luca M.", "text" => "Pacco arrivato prima del previsto, imballaggio perfetto."),
    array("name" => "Giovanni B.", "text" => "La consegna è stata veloce e puntuale."),
    array("name" => "Paolo T.", "text" => "Tutto è andato perfettamente, dall'ordine alla ricezione."),
    array("name" => "Stefano R.", "text" => "Imballaggio sicuro e consegna rapida."),
    array("name" => "Francesco L.", "text" => "Ho ricevuto il pacco in condizioni perfette."),
    array("name" => "Andrea G.", "text" => "Il corriere è stato molto professionale."),
    array("name" => "Matteo F.", "text" => "Consegna puntuale e prodotto ben protetto."),
    array("name" => "Davide P.", "text" => "Ottima esperienza d'acquisto, consiglio vivamente."),
    array("name" => "Alessandro B.", "text" => "Tutto come descritto, consegna velocissima."),
    array("name" => "Lorenzo C.", "text" => "Servizio impeccabile dall'inizio alla fine."),
    array("name" => "Simone V.", "text" => "Ho apprezzato molto la velocità di spedizione."),
    array("name" => "Federico D.", "text" => "Imballaggio curato nei minimi dettagli."),
    array("name" => "Giacomo E.", "text" => "Consegna rapida e senza problemi."),
    array("name" => "Riccardo H.", "text" => "Tutto perfetto, pacco integro."),
    array("name" => "Fabio I.", "text" => "Servizio di alta qualità, molto soddisfatto."),
    array("name" => "Enrico J.", "text" => "La consegna è arrivata anche prima del previsto."),
    array("name" => "Pietro K.", "text" => "Ottimo servizio clienti e consegna veloce."),
    array("name" => "Claudio L.", "text" => "Pacco arrivato in perfette condizioni."),
    array("name" => "Massimo M.", "text" => "Esperienza d'acquisto molto positiva."),
    array("name" => "Alberto N.", "text" => "Consegna rapida e imballaggio sicuro."),
    array("name" => "Sergio O.", "text" => "Tutto è andato alla perfezione."),
    array("name" => "Roberto P.", "text" => "Ho ricevuto tutte le informazioni di tracciamento."),
    array("name" => "Giorgio Q.", "text" => "Servizio eccellente, lo consiglio."),
    array("name" => "Carlo R.", "text" => "Pacco ben imballato e consegna puntuale."),
    array("name" => "Vincenzo S.", "text" => "Tutto perfetto, dalla A alla Z."),
    array("name" => "Michele T.", "text" => "Consegna velocissima e prodotto intatto."),
    array("name" => "Antonio U.", "text" => "Servizio clienti disponibile e cortese."),
    array("name" => "Franco V.", "text" => "Ho apprezzato la professionalità del servizio."),
    array("name" => "Bruno W.", "text" => "Consegna senza intoppi, tutto perfetto."),
    array("name" => "Enzo X.", "text" => "Pacco arrivato prima del tempo stimato."),
    array("name" => "Maurizio Y.", "text" => "Imballaggio eccellente, prodotto protetto."),
    array("name" => "Salvatore Z.", "text" => "Tutto come promesso, consegna veloce."),
    array("name" => "Angelo A.", "text" => "Servizio di consegna impeccabile."),
    array("name" => "Vittorio B.", "text" => "Ho ricevuto il pacco in tempi record."),
    array("name" => "Raffaele C.", "text" => "Ottima comunicazione durante tutta la spedizione."),
    array("name" => "Domenico D.", "text" => "Consegna rapida e sicura."),
    array("name" => "Pasquale E.", "text" => "Tutto è arrivato in perfette condizioni."),
    array("name" => "Gennaro F.", "text" => "Servizio di alta qualità, molto professionale."),
    array("name" => "Carmine G.", "text" => "Imballaggio curato e consegna veloce."),
    array("name" => "Alfredo H.", "text" => "Ho apprezzato molto l'efficienza del servizio."),
    array("name" => "Emanuele I.", "text" => "Pacco integro e consegna puntuale."),
    array("name" => "Filippo J.", "text" => "Esperienza molto positiva, consiglio."),
    array("name" => "Leonardo K.", "text" => "Tutto perfetto dall'ordine alla consegna.")
);
?>
