<?php
$auto_reviews_en = array(
    array("name" => "Marco E.", "text" => "Il colore rimane lo stesso anche dopo molti lavaggi."),
    array("name" => "Giovanni H.", "text" => "La maglietta Noriks mi ha davvero sorpreso. Il materiale è piacevole sulla pelle e il taglio segue la figura senza stringere. Anche dopo una giornata intera, resta fresca."),
    array("name" => "Tommaso V.", "text" => "Sembra moderna e lussuosa, anche se il prezzo è molto accessibile."),
    array("name" => "Daniele B.", "text" => "La indosso ogni giorno."),
    array("name" => "Cristiano L.", "text" => "All'inizio non ero sicuro, ma ha superato le mie aspettative. Ne comprerò altre."),
    array("name" => "Vittorio I.", "text" => "Design minimalista, si abbina a tutto."),
    array("name" => "Roberto S.", "text" => "Dopo dieci lavaggi ancora come nuova."),
    array("name" => "Nicola H.", "text" => "Non si vede il sudore."),
    array("name" => "Mario U.", "text" => "Veste bene sia alle figure snelle che a quelle più robuste."),
    array("name" => "Andrea P.", "text" => "Noriks è diventato il mio standard quotidiano. Morbida ma resistente e mantiene la forma. La taglia corrisponde alla tabella."),
    array("name" => "Matteo K.", "text" => "Il materiale è leggero ma non trasparente."),
    array("name" => "Davide Z.", "text" => "Maglietta molto comoda. Ne ho già ordinata un'altra. Si abbina praticamente a tutto."),
    array("name" => "Luca I.", "text" => "Si abbina a tutti i colori."),
    array("name" => "Giovanni L.", "text" => "Abbastanza lunga da restare nei pantaloni."),
    array("name" => "Biagio H.", "text" => "Il materiale non irrita la pelle nemmeno quando si suda."),
    array("name" => "Antonio J.", "text" => "Per lo sport e per la città."),
    array("name" => "Giorgio G.", "text" => "Materiale morbido ma resistente."),
    array("name" => "Stefano T.", "text" => "La qualità si vede a prima vista."),
    array("name" => "Bruno C.", "text" => "Semplice ma moderna."),
    array("name" => "Daniele P.", "text" => "Ho ricevuto più di quanto mi aspettassi."),
    array("name" => "Michele U.", "text" => "L'ho portata in viaggio – non si è stropicciata neanche dopo ore in valigia."),
    array("name" => "Giovanni R.", "text" => "Super leggera e comoda."),
    array("name" => "Tommaso L.", "text" => "La indosso sia con la giacca che con i pantaloni della tuta."),
    array("name" => "Nicola O.", "text" => "Colori resistenti."),
    array("name" => "Mario E.", "text" => "Ne ho già cinque."),
    array("name" => "Giorgio T.", "text" => "Ottimo aspetto e funzionalità."),
    array("name" => "Marco M.", "text" => "Al tatto sembra premium."),
    array("name" => "Roberto L.", "text" => "Sembra maschile ed elegante."),
    array("name" => "Antonio J.", "text" => "La indosso quasi a giorni alterni – sempre in rotazione."),
    array("name" => "Nicola T.", "text" => "Morbida come il cotone, ma più resistente."),
    array("name" => "Alessandro M.", "text" => "Il materiale è morbido ma non si allarga neanche dopo molti lavaggi."),
    array("name" => "Filippo P.", "text" => "Noriks mi ha conquistato già dalla prima volta. Traspirante e non aderisce alla pelle."),
    array("name" => "Bruno L.", "text" => "Lunghezza delle maniche ideale."),
    array("name" => "Giacomo F.", "text" => "Cercavo un modello così da tempo. Grazie!"),
    array("name" => "Cristiano B.", "text" => "Molto resistente — dopo molti utilizzi ancora come nuova."),
    array("name" => "Tommaso T.", "text" => "Lussuosa al tatto."),
    array("name" => "Pietro N.", "text" => "Sta benissimo con la giacca."),
    array("name" => "Davide V.", "text" => "Dopo diversi lavaggi nessun segno di usura. Ne comprerò altre."),
    array("name" => "Igor N.", "text" => "Non si stropiccia neanche dopo tutto il giorno."),
    array("name" => "Norberto U.", "text" => "Il colore è ancora più bello dal vivo."),
    array("name" => "Sandro Z.", "text" => "Facile da stirare."),
    array("name" => "Marco Z.", "text" => "Sono entusiasta! Ha soddisfatto tutto quello che cercavo."),
    array("name" => "Adriano L.", "text" => "Si abbina a tutti i pantaloni."),
    array("name" => "Antonio F.", "text" => "Veste bene anche se sono tra due taglie."),
    array("name" => "Giovanni K.", "text" => "Taglia perfetta."),
    array("name" => "Gianna G.", "text" => "La maglietta ideale per l'uomo moderno."),
    array("name" => "Domenico M.", "text" => "Un classico con un tocco di stile."),
    array("name" => "Raffaele A.", "text" => "Stile sportivo con una finitura elegante."),
    array("name" => "Mario H.", "text" => "Per l'ufficio e per il tempo libero."),
    array("name" => "Luca I.", "text" => "Non tira sotto le ascelle."),
    array("name" => "Giovanni M.", "text" => "Il taglio è perfetto anche per chi è più alto."),
    array("name" => "Stefano K.", "text" => "Ho trovato la mia nuova maglietta preferita."),
    array("name" => "Bogdan S.", "text" => "Ideale per viaggiare – leggera e compatta."),
    array("name" => "Francesco C.", "text" => "L'ho indossata a un colloquio – mi sono sentito sicuro di me."),
    array("name" => "Tommaso H.", "text" => "Lunghezza e taglio perfetti."),
    array("name" => "Nicola G.", "text" => "La indosso al lavoro e in città."),
    array("name" => "Vladimiro G.", "text" => "Elegante e comoda."),
    array("name" => "Giuseppe L.", "text" => "L'equilibrio ideale tra eleganza e comfort."),
    array("name" => "Luca T.", "text" => "Ottima per l'allenamento e l'uso quotidiano."),
    array("name" => "Giovanni J.", "text" => "Qualità oltre il prezzo."),
    array("name" => "Leone Z.", "text" => "Mantiene forma e colore."),
    array("name" => "Biagio E.", "text" => "Si può facilmente adattare a uno stile più formale."),
    array("name" => "Mario T.", "text" => "Ho ricevuto molti complimenti."),
    array("name" => "Cristiano H.", "text" => "Non raccoglie peli."),
    array("name" => "Tiberio V.", "text" => "Dura tutto il giorno."),
    array("name" => "Filippo Z.", "text" => "Una maglietta per ogni occasione."),
    array("name" => "Roberto V.", "text" => "Comoda tutto il giorno."),
    array("name" => "Mirco D.", "text" => "Design minimalista e maschile."),
    array("name" => "Sandro O.", "text" => "Funziona ogni giorno."),
    array("name" => "Roberto G.", "text" => "Il miglior acquisto online."),
    array("name" => "Antonio G.", "text" => "La mia prima scelta ogni mattina."),
    array("name" => "Davide L.", "text" => "Veste come un guanto."),
    array("name" => "Cristiano V.", "text" => "Il taglio è davvero perfetto — segue la linea senza stringere."),
    array("name" => "Alessandro W.", "text" => "Sembra più costosa di quello che è."),
    array("name" => "Emilio W.", "text" => "Sembra lussuosa."),
    array("name" => "Valerio U.", "text" => "Il materiale è morbido ma non mostra segni di usura."),
    array("name" => "Tiberio E.", "text" => "Le maniche non sono troppo strette."),
    array("name" => "Pietro M.", "text" => "Da tempo non ero così soddisfatto di una semplice maglietta."),
    array("name" => "Domenico T.", "text" => "Per passeggiate e uscite serali."),
    array("name" => "Bruno K.", "text" => "Non si deforma."),
    array("name" => "Antonio I.", "text" => "La maglietta più comoda di questa stagione."),
    array("name" => "Siniša P.", "text" => "Si asciuga velocemente."),
    array("name" => "Carlo U.", "text" => "Stile casual che mi piace."),
    array("name" => "Nicola Z.", "text" => "Ottimo rapporto qualità-prezzo."),
    array("name" => "Fabiano R.", "text" => "Si stropiccia poco — ideale."),
    array("name" => "Zlatko F.", "text" => "Finalmente una maglietta moderna senza sacrificare il comfort."),
    array("name" => "Mario P.", "text" => "La consiglio al cento per cento."),
    array("name" => "Giuseppe X.", "text" => "Leggera per l'estate, ideale per stratificare."),
    array("name" => "Vladimiro K.", "text" => "È diventata la mia preferita."),
    array("name" => "Erik J.", "text" => "Dal vivo è ancora meglio che nelle foto."),
    array("name" => "Tommaso S.", "text" => "Aspetto e sensazione speciali."),
    array("name" => "Carlo Z.", "text" => "Altrettanto buona anche sotto un maglione."),
    array("name" => "Zbigniew N.", "text" => "Non scivola dalle spalle."),
    array("name" => "Giovanni D.", "text" => "Comoda e professionale."),
    array("name" => "Nino G.", "text" => "Resta fresca tutto il giorno."),
    array("name" => "Luca M.", "text" => "Finalmente una maglietta anche per chi è più alto."),
    array("name" => "Bruno T.", "text" => "Così comoda che è come un pigiama."),
    array("name" => "Filippo K.", "text" => "Lunghezza ideale – non esce dai pantaloni."),
    array("name" => "Tommaso J.", "text" => "Si asciuga velocemente – ideale per i viaggi."),
    array("name" => "Stefano M.", "text" => "Ottima non solo per l'aspetto, ma anche per la sensazione."),
    array("name" => "Giorgio V.", "text" => "Se cercate qualità — questa è quella giusta."),
    array("name" => "Davide I.", "text" => "Pratica e moderna."),
    array("name" => "Željko B.", "text" => "Ogni outfit sembra migliore."),
    array("name" => "Nevio D.", "text" => "Cinque su cinque anche dalla ragazza."),
    array("name" => "Vedran G.", "text" => "Dopo ogni lavaggio come nuova."),
    array("name" => "Giovanni Z.", "text" => "Parte del mio outfit quotidiano."),
    array("name" => "Cristiano D.", "text" => "Perfetto equilibrio tra sport ed eleganza."),
    array("name" => "Michele R.", "text" => "Mantiene forma e colore."),
    array("name" => "Matteo V.", "text" => "Veste perfettamente in ogni direzione."),
    array("name" => "Filippo F.", "text" => "Non cambia forma dopo il lavaggio."),
    array("name" => "Alessandro C.", "text" => "Il colore resiste anche dopo molti cicli."),
    array("name" => "Cristiano P.", "text" => "Il taglio segue la figura senza fastidio."),
    array("name" => "Biagio K.", "text" => "Veste bene anche su figure più robuste."),
    array("name" => "Tommaso G.", "text" => "Resistente anche dopo lo sport."),
    array("name" => "Andrea N.", "text" => "Traspirante anche durante una giornata impegnativa."),
    array("name" => "Antonio K.", "text" => "Il materiale sembra davvero di qualità."),
    array("name" => "Sandro R.", "text" => "Ha retto 12 ore di lavoro."),
    array("name" => "Giovanni N.", "text" => "Cercavo una maglietta così da anni."),
    array("name" => "Domenico R.", "text" => "Si abbina a tutto."),
    array("name" => "Luca W.", "text" => "Ottima alternativa alla camicia."),
    array("name" => "Emilio T.", "text" => "Soluzione ideale per ogni giorno."),
    array("name" => "Roberto N.", "text" => "Mantiene la qualità anche dopo un mese di lavaggi."),
    array("name" => "Mario Q.", "text" => "Nessun fastidio neanche dopo tutto il giorno."),
    array("name" => "Cristiano J.", "text" => "Per il lavoro e per il tempo libero."),
    array("name" => "Giuseppe E.", "text" => "Veste perfettamente."),
    array("name" => "Željko F.", "text" => "Anche dopo molti utilizzi ancora come nuova."),
    array("name" => "Davide W.", "text" => "Comoda in ogni posizione."),
    array("name" => "Luca B.", "text" => "La indosso ogni giorno."),
    array("name" => "Carlo D.", "text" => "Sembra fatta su misura."),
    array("name" => "Siniša G.", "text" => "Ottima anche quando si suda."),
    array("name" => "Branimir V.", "text" => "Non si allarga dopo il lavaggio."),
    array("name" => "Damiano S.", "text" => "Ideale per stratificare."),
    array("name" => "Antonio V.", "text" => "Fresca tutto il giorno."),
    array("name" => "Tony L.", "text" => "Piacevole anche al sole."),
    array("name" => "Nicola L.", "text" => "Tanti complimenti."),
    array("name" => "Bruno M.", "text" => "Prodotto eccezionale — dovevo scrivere una recensione."),
    array("name" => "Giovanni K.", "text" => "Facile manutenzione, asciugatura rapida."),
    array("name" => "Giorgio S.", "text" => "I dettagli al collo sono di alta qualità."),
    array("name" => "Bruno G.", "text" => "Sembra fatta per durare anni."),
    array("name" => "Valerio C.", "text" => "Valorizza la figura e non è trasparente."),
    array("name" => "Filippo O.", "text" => "Ottimo servizio."),
    array("name" => "Marco D.", "text" => "Ne ho comprata una e subito ne ho ordinate altre tre."),
    array("name" => "Tommaso P.", "text" => "Comoda tutto il giorno."),
    array("name" => "Stefano P.", "text" => "Sufficientemente elastica."),
    array("name" => "Michele S.", "text" => "Lavorazione di qualità."),
    array("name" => "Vittorio I.", "text" => "Non aderisce neanche quando si suda."),
    array("name" => "Antonio R.", "text" => "Semplicemente perfetta."),
    array("name" => "Luca R.", "text" => "La maglietta più comoda che ho."),
    array("name" => "Nicola A.", "text" => "Ottima anche in inverno sotto la felpa."),
    array("name" => "Roberto E.", "text" => "Le recensioni non mentivano."),
    array("name" => "Andrea J.", "text" => "Ottimo investimento."),
    array("name" => "Davide H.", "text" => "Taglio e comfort perfetti."),
    array("name" => "Biagio P.", "text" => "Tutto al massimo."),
    array("name" => "Miroslav Z.", "text" => "Grazie al taglio sembro più curato."),
    array("name" => "Filippo B.", "text" => "Il miglior adattamento al corpo."),
    array("name" => "Cristiano E.", "text" => "Piacevole sulla pelle, nessun segno."),
    array("name" => "Marino D.", "text" => "Non raccoglie polvere né peli."),
    array("name" => "Giovanni D.", "text" => "Ideale per chi vuole comfort e stile."),
    array("name" => "Carlo N.", "text" => "Neanche al sole faceva caldo."),
    array("name" => "Mario K.", "text" => "Moderna ma non esagerata."),
    array("name" => "Željko E.", "text" => "Tutto corrisponde alla realtà."),
    array("name" => "Siniša H.", "text" => "Aspetto pulito e semplice."),
    array("name" => "Damiano V.", "text" => "Per il lavoro e per uscire la sera."),
    array("name" => "Borislav J.", "text" => "Nessun logo, solo stile."),
    array("name" => "Daniele K.", "text" => "Minimalismo che funziona."),
    array("name" => "Giacomo P.", "text" => "Ne ho ordinate altre due."),
    array("name" => "Leone F.", "text" => "La leggera lucentezza sembra elegante."),
    array("name" => "Giacomo J.", "text" => "Il taglio valorizza la figura."),
    array("name" => "Valerio R.", "text" => "Da tempo non ero così soddisfatto."),
    array("name" => "Tiberio B.", "text" => "Perfetta per ogni giorno."),
    array("name" => "Michele K.", "text" => "Molto piacevole sulla pelle."),
    array("name" => "Andrea V.", "text" => "Qualità costante ogni settimana."),
    array("name" => "Davide C.", "text" => "Vale davvero la pena."),
    array("name" => "Tommaso N.", "text" => "Sopporta anche l'asciugatrice."),
    array("name" => "Bruno U.", "text" => "Ce l'ho in più colori."),
    array("name" => "Alessandro T.", "text" => "Effetto wow fin dalla prima volta."),
    array("name" => "Stefano H.", "text" => "Il colletto tiene perfettamente."),
    array("name" => "Domenico E.", "text" => "La migliore maglietta che abbia mai avuto."),
    array("name" => "Antonio H.", "text" => "Esattamente quello che cercavo."),
    array("name" => "Filippo L.", "text" => "Ottima lavorazione."),
    array("name" => "Cristiano T.", "text" => "Leggera ma resistente."),
    array("name" => "Giovanni O.", "text" => "Sensazione di libertà."),
    array("name" => "Pietro B.", "text" => "Ottima anche con l'umidità."),
    array("name" => "Francesco D.", "text" => "Ne ho comprate di più."),
    array("name" => "Nicola M.", "text" => "Elastica e comoda."),
    array("name" => "Giovanni R.", "text" => "Funziona in estate e in inverno."),
    array("name" => "Mario F.", "text" => "Sembra professionale."),
    array("name" => "Željko C.", "text" => "Resiste anche all'uso intensivo."),
    array("name" => "Vladimiro F.", "text" => "Mantiene la forma anche dopo molti lavaggi."),
    array("name" => "Antonio J.", "text" => "Meglio dei marchi costosi."),
    array("name" => "Luca V.", "text" => "Resta salda tutto il giorno."),
    array("name" => "Nicola V.", "text" => "Dopo mesi ancora come nuova."),
    array("name" => "Cristiano N.", "text" => "Densità del materiale perfetta."),
    array("name" => "Borislav C.", "text" => "Ha vestito bene fin dalla prima volta."),
    array("name" => "Marco U.", "text" => "Lunghezza e spalle perfette."),
    array("name" => "Michele S.", "text" => "Molto soddisfatto."),
    array("name" => "Giorgio J.", "text" => "Minimalismo che funziona."),
    array("name" => "Kresimir Y.", "text" => "Mi sento sicuro di me."),
    array("name" => "Vedran F.", "text" => "Maglietta quotidiana perfetta."),
    array("name" => "Davide O.", "text" => "Piacevole sorpresa."),
    array("name" => "Nicola H.", "text" => "Il colletto tiene anche dopo l'asciugatrice."),
    array("name" => "Tiberio G.", "text" => "Sicuramente la comprerò di nuovo."),
    array("name" => "Angelo M.", "text" => "La texture è fantastica."),
    array("name" => "Zarko T.", "text" => "Consegna veloce."),
    array("name" => "Nicola J.", "text" => "Perfetta nelle spalle."),
    array("name" => "Andrea P.", "text" => "Miglior rapporto qualità-prezzo."),
    array("name" => "Alessandro J.", "text" => "Come fatta su misura."),
    array("name" => "Vladimiro C.", "text" => "Consegna veloce, imballaggio perfetto."),
    array("name" => "Davide I.", "text" => "Per il sabato e per la cena."),
    array("name" => "Carlo M.", "text" => "Nessuna irritazione della pelle."),
    array("name" => "Francesco P.", "text" => "Nessun odore neanche dopo tutto il giorno."),
    array("name" => "Zoran L.", "text" => "Figura otticamente migliore."),
    array("name" => "Igor S.", "text" => "Ordine semplice."),
    array("name" => "Antonio D.", "text" => "Prendo un altro colore."),
    array("name" => "Andrea K.", "text" => "Mi sento meglio con questa."),
    array("name" => "Michele N.", "text" => "Non serve stirare."),
    array("name" => "Giorgio P.", "text" => "Cuciture morbide."),
    array("name" => "Giovanni G.", "text" => "Ideale per l'ufficio."),
    array("name" => "Leo C.", "text" => "Il colore corrisponde alle foto."),
    array("name" => "Damiano P.", "text" => "Sembra più costosa."),
    array("name" => "Ervin S.", "text" => "Morbida e solida."),
    array("name" => "Valerio M.", "text" => "Resistente anche con uso frequente."),
    array("name" => "Nicola V.", "text" => "Il materiale respinge le macchie."),
    array("name" => "Stefano O.", "text" => "La XL veste perfettamente."),
    array("name" => "Bruno R.", "text" => "Linee pulite."),
    array("name" => "Antonio Š.", "text" => "Dalla palestra al caffè."),
    array("name" => "Michele P.", "text" => "Il grigio sta benissimo."),
    array("name" => "Filippo G.", "text" => "Comoda anche in viaggio."),
    array("name" => "Giovanni Y.", "text" => "La mia raccomandazione."),
    array("name" => "Carlo P.", "text" => "Mantiene la forma anche sotto la camicia."),
    array("name" => "Matteo D.", "text" => "Stile senza sforzo."),
    array("name" => "Emilio C.", "text" => "Totale soddisfazione.")
);
?>
