<?php
$auto_reviews_en = array(
    array("name" => "Giorgio M.", "text" => "Il colore dei boxer resta lo stesso anche dopo molti lavaggi, non sbiadisce."),
    array("name" => "Antonio B.", "text" => "Tessuto traspirante e piacevole sulla pelle."),
    array("name" => "Marco S.", "text" => "Boxer davvero comodi per tutto il giorno, quasi non li sento."),
    array("name" => "Luca R.", "text" => "Il miglior intimo che abbia mai comprato."),
    array("name" => "Giovanni P.", "text" => "Non si arrotolano mai, perfetti."),
    array("name" => "Davide T.", "text" => "Morbidi e traspiranti, esattamente quello che cercavo."),
    array("name" => "Francesco L.", "text" => "Dopo molti lavaggi ancora come nuovi."),
    array("name" => "Alessandro V.", "text" => "Il tessuto non irrita, perfetto per pelli sensibili."),
    array("name" => "Matteo G.", "text" => "La vestibilità è fantastica, non stringono."),
    array("name" => "Stefano C.", "text" => "Molto meglio dei miei vecchi boxer."),
    array("name" => "Andrea F.", "text" => "Il materiale è leggero ma resistente."),
    array("name" => "Roberto N.", "text" => "Non mi aspettavo questa qualità a questo prezzo."),
    array("name" => "Nicola H.", "text" => "I boxer Noriks sono la mia prima scelta nel cassetto."),
    array("name" => "Paolo K.", "text" => "Comfort assoluto, li indosso tutti i giorni."),
    array("name" => "Michele Z.", "text" => "Ottimo rapporto qualità-prezzo."),
    array("name" => "Fabio E.", "text" => "Non si vede il sudore, molto traspiranti."),
    array("name" => "Simone D.", "text" => "Perfetti per lo sport e la vita quotidiana."),
    array("name" => "Lorenzo B.", "text" => "Il taglio è studiato perfettamente per il corpo maschile."),
    array("name" => "Giacomo W.", "text" => "Hanno sostituito tutti i miei vecchi boxer."),
    array("name" => "Federico A.", "text" => "Cuciture morbide, nessun fastidio."),
    array("name" => "Riccardo I.", "text" => "Il tessuto è premium, si sente subito."),
    array("name" => "Enrico O.", "text" => "Finalmente dei boxer che non si allargano."),
    array("name" => "Claudio U.", "text" => "Vestono perfettamente anche chi ha cosce più robuste."),
    array("name" => "Pietro J.", "text" => "Sono diventati i miei preferiti."),
    array("name" => "Bruno Q.", "text" => "Non si arrotolano neanche durante lo sport."),
    array("name" => "Carlo X.", "text" => "Il materiale modal è una rivelazione."),
    array("name" => "Dario Y.", "text" => "Primi boxer che non mi danno fastidio."),
    array("name" => "Emilio F.", "text" => "Elastico che non stringe ma tiene."),
    array("name" => "Giorgio S.", "text" => "Comfort tutto il giorno, anche in estate."),
    array("name" => "Vincenzo T.", "text" => "Il colore resta vivido anche dopo molti lavaggi."),
    array("name" => "Angelo R.", "text" => "Spazio sufficiente dove serve."),
    array("name" => "Salvatore P.", "text" => "Non sapevo che i boxer potessero essere così comodi."),
    array("name" => "Mario C.", "text" => "Zero irritazioni, perfetti per la pelle sensibile."),
    array("name" => "Franco L.", "text" => "Il miglior acquisto dell'anno."),
    array("name" => "Enzo M.", "text" => "Resistenti e morbidi allo stesso tempo."),
    array("name" => "Maurizio V.", "text" => "Non si deformano dopo il lavaggio."),
    array("name" => "Raffaele G.", "text" => "Li indosso dalla mattina alla sera senza problemi."),
    array("name" => "Domenico H.", "text" => "Tessuto che si asciuga velocemente."),
    array("name" => "Pasquale B.", "text" => "Hanno cambiato il mio modo di pensare ai boxer."),
    array("name" => "Gennaro K.", "text" => "Questi boxer meritano una recensione."),
    array("name" => "Carmine E.", "text" => "Nessun pizzicore o fastidio, solo comfort."),
    array("name" => "Alfredo D.", "text" => "Ottima vestibilità per tutte le taglie."),
    array("name" => "Emanuele N.", "text" => "I migliori boxer che abbia mai comprato."),
    array("name" => "Filippo O.", "text" => "Il tessuto è traspirante anche nelle giornate calde."),
    array("name" => "Leonardo I.", "text" => "Finalmente boxer che non stringono."),
    array("name" => "Tommaso U.", "text" => "Li ho comprati per provarli, ora ne ho già cinque paia."),
    array("name" => "Daniele A.", "text" => "Perfetti per chi fa sport."),
    array("name" => "Alberto Z.", "text" => "Il materiale è incredibilmente morbido."),
    array("name" => "Sergio W.", "text" => "Non tornerei mai ai miei vecchi boxer."),
    array("name" => "Massimo J.", "text" => "Comfort e stile insieme."),
    array("name" => "Vittorio Q.", "text" => "Tessuto che non perde colore."),
    array("name" => "Biagio X.", "text" => "Ideali per il caldo estivo."),
    array("name" => "Tiberio Y.", "text" => "Li consiglio a tutti i miei amici."),
    array("name" => "Adriano F.", "text" => "Elastico perfetto, non lascia segni."),
    array("name" => "Norberto S.", "text" => "Finalmente ho trovato i boxer giusti."),
    array("name" => "Sandro T.", "text" => "Qualità top a un prezzo accessibile."),
    array("name" => "Mirko R.", "text" => "Si adattano perfettamente al corpo."),
    array("name" => "Damiano P.", "text" => "Non sapevo che esistessero boxer così comodi."),
    array("name" => "Fabiano C.", "text" => "Tessuto leggero e resistente."),
    array("name" => "Zlatko L.", "text" => "Dopo mesi di utilizzo ancora come nuovi."),
    array("name" => "Vedran M.", "text" => "Il miglior intimo maschile sul mercato."),
    array("name" => "Branimir V.", "text" => "Zero problemi di vestibilità."),
    array("name" => "Nevio G.", "text" => "Ottimi per ogni occasione."),
    array("name" => "Kresimir H.", "text" => "Hanno superato le mie aspettative."),
    array("name" => "Zvonimir B.", "text" => "Consiglio a tutti di provarli."),
    array("name" => "Bojan K.", "text" => "Comfort dalla mattina alla sera."),
    array("name" => "Hrvoje E.", "text" => "Non potrei essere più soddisfatto."),
    array("name" => "Damir D.", "text" => "Perfetti in ogni dettaglio."),
    array("name" => "Zoran N.", "text" => "Il tessuto modal fa davvero la differenza."),
    array("name" => "Igor O.", "text" => "Boxer che meritano ogni stella."),
    array("name" => "Siniša I.", "text" => "Non stringono e non si arrotolano."),
    array("name" => "Željko U.", "text" => "Qualità eccezionale."),
    array("name" => "Stanko A.", "text" => "Morbidezza incredibile."),
    array("name" => "Vlado Z.", "text" => "Il miglior acquisto online che abbia fatto."),
    array("name" => "Mladen W.", "text" => "Tessuto che non irrita la pelle."),
    array("name" => "Tomislav J.", "text" => "Elastico che dura nel tempo."),
    array("name" => "Zdravko Q.", "text" => "Perfetti anche per le cosce più robuste."),
    array("name" => "Kristijan X.", "text" => "Non mi aspettavo tanta qualità."),
    array("name" => "Domagoj Y.", "text" => "Li indosso tutti i giorni."),
    array("name" => "Blaž F.", "text" => "Comfort assoluto in ogni situazione."),
    array("name" => "Dino S.", "text" => "Non tornerei mai indietro."),
    array("name" => "Miro T.", "text" => "Qualità che si sente."),
    array("name" => "Alen R.", "text" => "Perfetti per ogni stagione."),
    array("name" => "Josip P.", "text" => "Il miglior intimo che abbia mai provato."),
    array("name" => "Nino C.", "text" => "Tessuto premium a un prezzo giusto."),
    array("name" => "Ante L.", "text" => "Finalmente dei boxer all'altezza."),
    array("name" => "Goran M.", "text" => "Li consiglio vivamente."),
    array("name" => "Darko V.", "text" => "Comfort e durabilità insieme.")
);
?>
